import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}
      >
        <header>
          <div className="flex flex-col items-center justify-center gap-4 p-6">
            <h1 className="text-xl font-bold text-center">
              Leading companies in the field of AI
            </h1>
            <h2>
              Aidan Daly's Vercel Coding Challenge
            </h2>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
